blank_issues_enabled: false
contact_links:
  - name: Submit your issues here
    url: https://github.com/War-Brokers/War-Brokers/issues
    about:
  - name: Discord Server
    url: https://discord.gg/synPSeuNFK
    about:
