name: Sync labels

on:
  push:
    branches:
      - master
    paths:
      - .github/labels.yml
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - uses: micnncim/action-label-syncer@v1
        with:
          repository: |
            War-Brokers/War-Brokers
            War-Brokers/.github
          token: ${{ secrets.DEVELOPOMP_PAT }}
